version: '3.3'

services:
  odoo:
#    platform: linux/amd64 # for run on arm cpu
    build: .
    # image: mink
    image: mink_nginx
    container_name: odoo
    restart: always
    deploy:
      resources:
        limits:
          memory: 6.5g
          cpus: '3.5'
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/lib/odoo:/var/lib/odoo
      - /var/log/odoo:/var/log/odoo
      - /mnt/addons:/mnt/addons
      - ./config/odoo.conf:/etc/odoo.conf
    environment:
    - "OPTIONS=${COMPOSE_OPTIONS:--update=base}"
    - "USER_ID=101"
    - "GROUP_ID=101"
    logging:
      options:
        max-size: "10m"
        max-file: "3"
    tty: true
    command: odoo

